### PR TITLE
user_details v1 api

### LINKED ISSUE #7246: T - user details v1 API endpoint
**Summary**
So you can use the new Account Settings (user details) page via an API. 
It needs to support getting as well as updating the user details. 

**Proposal**
The following user data fields are needed:

* `is_newsletter_subscribed`
* `username`
* `fullname`
* `locale`

**Additional context**
A prototype of the new user details (as part of account settings) is already in master except it doesn't prefill the from server data and it doesn't have a submit handler.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #7246

Hopefully the "unit tests" speak for themselves. But what I did, to sanity check that it would work was this quick hack to user-details.jsx:

```diff
diff --git a/kuma/javascript/src/accountsettings/components/user-details.jsx b/kuma/javascript/src/accountsettings/components/user-details.jsx
index 72309db8a..1b5a908e8 100644
--- a/kuma/javascript/src/accountsettings/components/user-details.jsx
+++ b/kuma/javascript/src/accountsettings/components/user-details.jsx
@@ -1,7 +1,9 @@
 // @flow
 import * as React from 'react';
+import { useEffect } from 'react';
 
 import { gettext } from '../../l10n.js';
+import { getCookie } from '../../utils';
 import LanguageSelect from './language-select.jsx';
 
 type Props = {
@@ -13,6 +15,32 @@ type Props = {
 const UserDetails = ({ locale, userData, sortedLanguages }: Props) => {
     const { email, username } = userData;
 
+    useEffect(() => {
+        let dismounted = false;
+        fetch('/api/v1/user_details/')
+            .then((response) => response.json())
+            .then((data) => {
+                console.log('DATA:', data);
+                // data['fullname'] += ' new';
+                fetch('/api/v1/user_details/', {
+                    method: 'PUT',
+                    body: JSON.stringify(data),
+                    headers: {
+                        'X-CSRFToken': getCookie('csrftoken'),
+                        'Content-Type': 'application/json',
+                    },
+                })
+                    .then((response) => response.json())
+                    .then((r) => {
+                        console.log('PUTTED:', r);
+                    });
+            });
+
+        return () => {
+            dismounted = true;
+        };
+    }, []);
+
     return (
         <form
             name="user-details"
```

And it works. I don't think you need to apply that diff but if you skim it you can see what's possible and to be done in the React world once this endpoint is in place.

### CODE REVIEW

**Comment by peterbe** [comment]
CC @schalkneethling

**Comment by peterbe** [comment]
@Gregoor How about: you merge this, when it's green, since its conflicts are resolved. Then, when you work on the conflicts in https://github.com/mdn/kuma/pull/7267 you can weave these in too. Deal?

**Comment by schalkneethling** [comment]
Thank you @Gregoor and @peterbe o/\o - I guess now we need an issue to wire up the UI with the backend. I will it so.

**Comment by schalkneethling** [comment]
https://github.com/mdn/kuma/issues/7279 - And here is the task.

**Pull request merged**
