### PR TITLE
Update redis dependencies

### PR DESCRIPTION
**Pull request by callahad**
- Updating django-redis (4.10.0 -> 4.11.0)
  https://github.com/niwinz/django-redis/blob/4.11.0/CHANGES.txt

- Updating redis (3.2.1 -> 3.4.0)
  https://github.com/andymccurdy/redis-py/blob/3.4.0/CHANGES

Unpinning `redis` because we don't use it directly; it's pulled in by
`django-redis`. The minor version updates mainly seem related to
dropping support for older Python versions.

### CODE REVIEW

**Comment by peterbe** [comment]
@escattone @callahad 

This is breaking my `docker-compose` now:

```
worker_1         | [2020-02-03 11:57:30,239: CRITICAL/MainProcess] Unrecoverable error: TypeError("unhashable type: 'Redis'")
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 205, in start
worker_1         |     self.blueprint.start(self)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
worker_1         |     step.start(parent)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 369, in start
worker_1         |     return self.obj.start()
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
worker_1         |     blueprint.start(self)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
worker_1         |     step.start(parent)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/mingle.py", line 40, in start
worker_1         |     self.sync(c)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
worker_1         |     replies = self.send_hello(c)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
worker_1         |     replies = inspect.hello(c.hostname, our_revoked._data) or {}
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/control.py", line 154, in hello
worker_1         |     return self._request('hello', from_node=from_node, revoked=revoked)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/control.py", line 98, in _request
worker_1         |     return self._prepare(self.app.control.broadcast(
worker_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/control.py", line 475, in broadcast
worker_1         |     return self.mailbox(conn)._broadcast(
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 349, in _broadcast
worker_1         |     return self._collect(reply_ticket, limit=limit,
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/pidbox.py", line 391, in _collect
worker_1         |     self.connection.drain_events(timeout=timeout)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 323, in drain_events
worker_1         |     return self.transport.drain_events(self.connection, **kwargs)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events
worker_1         |     get(self._deliver, timeout=timeout)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 374, in get
worker_1         |     self._register_BRPOP(channel)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 311, in _register_BRPOP
worker_1         |     if not self._client_registered(channel, channel.client, 'BRPOP'):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 306, in _client_registered
worker_1         |     (channel, client, cmd) in self._chan_to_sock)
worker_1         | TypeError: unhashable type: 'Redis'
```

All I did was to check out master, rebuild everything and the `docker-compose up`. 

I *might* be able to do a drain or something of the Redis but I do worry that we might break prod.

**Comment by escattone** [comment]
@peterbe I think a `docker-compose pull` will fix your local issue.

**Comment by peterbe** [comment]
> @peterbe I think a `docker-compose pull` will fix your local issue.

Doesn't help. 

Do you not get this error in yours? Perhaps your Redis instance inside the docker image was drained.

**Comment by escattone** [comment]
@peterbe 

> Doesn't help.
> 
> Do you not get this error in yours? Perhaps your Redis instance inside the docker image was drained.

Just to be more clear, you'd need to do a `docker-compose pull` followed by `docker-compose down` (not a `docker-compose stop` since you need to re-create the containers with the new images) and then `docker-compose up -d`.

**Comment by callahad** [comment]
Ah weird, I'm seeing this now, too.

I'll dig into it for half an hour, and if I don't see anything obvious, we can revert this.

**Comment by callahad** [comment]
Shoot. This is a known regression in redis-py 3.4.0, fixed in 3.4.1. A quick `poetry update redis` will fix this, PR coming in just a sec.

**Comment by callahad** [comment]
Fixed in #6403 

It's unfortunate that our CI pipelines don't detect when the `worker` crashes on startup.

**Comment by escattone** [comment]
@peterbe @callahad Oh man, I'm seeing this too! Sorry I missed that earlier!

**Pull request merged**
