### PR TITLE
Fix dropdown menu position on RTL languages 

### LINKED ISSUE #6354: Language list dropdown is cut off for RTL languages
For example, https://developer.mozilla.org/ar/docs/Web :

Screen Shot 2020-01-17 at 9 10 32 AM

### PR DESCRIPTION
**Pull request by mindy**
- Move positioning of dropdown menu to SCSS file, so we can use the `bidi` mixin to handle LTR and RTL languages. 
- Affects both the User Avatar dropdown in the header and the language dropdown

**Sample URL:** 
http://localhost.org:8000/ar/docs/Web/CSS/:focus-visible

**Before:**
menu-before

**After:** 
menu-after

Closes #6354

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey @mindy, thank you for the PR. The Jest snapshot tests are failing because of the change in the `jsx` file. To update those snapshot tests, run the following and then add and commit the result:

```
npm t -- --u
```

https://jestjs.io/docs/en/snapshot-testing.html#updating-snapshots

**Comment by mindy** [comment]
> Hey @mindy, thank you for the PR. The Jest snapshot tests are failing because of the change in the `jsx` file. To update those snapshot tests, run the following and then add and commit the result:
> 
> ```
> npm t -- --u
> ```
> 
> https://jestjs.io/docs/en/snapshot-testing.html#updating-snapshots

Thanks @schalkneethling ! Do you think it's a good idea to add `npm run test` to the precommit hook to catch this sooner?

**Comment by schalkneethling** [comment]
> > Hey @mindy, thank you for the PR. The Jest snapshot tests are failing because of the change in the `jsx` file. To update those snapshot tests, run the following and then add and commit the result:
> > ```
> > npm t -- --u
> > ```
> > 
> > 
> > https://jestjs.io/docs/en/snapshot-testing.html#updating-snapshots
> 
> Thanks @schalkneethling ! Updated the snapshots. Do you think it's a good idea to add `npm run test` to the precommit hook to catch this sooner?

We can surely bring this up for a vote. We need to make sure everyone is ok with that. I know people have been a little concerned about adding too much, as it might over time make the commit process tedious.

**Comment by schalkneethling** [comment]
> > > Hey @mindy, thank you for the PR. The Jest snapshot tests are failing because of the change in the `jsx` file. To update those snapshot tests, run the following and then add and commit the result:
> > > ```
> > > npm t -- --u
> > > ```
> > > 
> > > 
> > > [jestjs.io/docs/en/snapshot-testing.html#updating-snapshots](https://jestjs.io/docs/en/snapshot-testing.html#updating-snapshots)
> > 
> > 
> > Thanks @schalkneethling ! Updated the snapshots. Do you think it's a good idea to add `npm run test` to the precommit hook to catch this sooner?
> 
> We can surely bring this up for a vote. We need to make sure everyone is ok with that. I know people have been a little concerned about adding too much, as it might over time make the commit process tedious.

@mindy I would suggest opening an issue and asking for input from the team. Thanks!

**Comment by mindy** [comment]
Thanks @schalkneethling ! Created https://github.com/mdn/kuma/issues/6437

**Pull request merged**
