### PR TITLE
comment out auth-started GA event for now

### PR DESCRIPTION
**Pull request by peterbe**
Part of #6759

I hope the code comment is sufficient to explain the rationale of this PR. 
Note that this doesn't close the issue.

### CODE REVIEW

**Comment by atopal** [comment]
Hey Peter, if I understand correctly, this doesn't actually do what the title says? I'd much rather turn event collection off for now and then turn it on again with client ID if we can, and in that case I don't much about bots, because GA will discount them anyway. The referrer solution would still count every event sent as an extra user on MDN.

**Comment by peterbe** [comment]
@atopal I updated the PR title. 
We can do another one where we actually turn it off. I guess you haven't had a chance yet to evaluate if this solved the problem of "rogue events".

**Comment by atopal** [comment]
Data just came in for April 1st. Down to 1k per day. Thanks Peter!

It still distorts the data, since without the client ID every event is counted as a separate users, but for the log in flow that should not be more than 30k "users" per month. We can live with that.

**Comment by peterbe** [comment]
> Data just came in for April 1st. Down to 1k per day. Thanks Peter!
> 
> It still distorts the data, since without the client ID every event is counted as a separate user, but for the log in flow that should not be more than 30k "users" per month. We can live with that.

@tobinmori @atopal So what does this mean? Shall we bother removing the instrumentation entirely? ...until we have that thing that puts the GA clientID into the web request?

**Comment by atopal** [comment]
No, it's fine, we can live with that for now and can decide later whether we still want to implement the client ID solution. If numbers stay this way it's just not enough noise to matter.

**Pull request merged**
