### PR TITLE
Don't serialize what can be extacted from DOM from SSR

### LINKED ISSUE #5613: Beta site HTML is larger
In beta.developer.mozilla.org the HTML payload is much larger. 

Comparing:

* https://beta.developer.mozilla.org/en-US/docs/Web/HTML/Element/link - 393K (59K gzipped)
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link - 225K (39K gzipped)

See:
https://htmltree.herokuapp.com/?url=https:%2F%2Fbeta.developer.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FHTML%2FElement%2Flink
https://htmltree.herokuapp.com/?url=https:%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FHTML%2FElement%2Flink

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #5613

An experiment that @Gregoor and I are playing with.

### CODE REVIEW

**Comment by peterbe** [comment]
Going with https://github.com/mozilla/kuma/pull/5771 instead.

**Comment by peterbe** [comment]
Actually, this one does work. At least in theory. 

```
-rw-r--r--   1 peterbe  wheel    29K Oct  4 16:41 after.html.gz
-rw-r--r--   1 peterbe  wheel   115K Oct  4 16:41 after.html
-rw-r--r--   1 peterbe  wheel    39K Oct  4 16:43 mdn.html.gz
-rw-r--r--   1 peterbe  wheel   161K Oct  4 16:43 mdn.html
-rw-r--r--   1 peterbe  wheel    48K Oct  4 16:59 before.html.gz
-rw-r--r--   1 peterbe  wheel   202K Oct  4 16:59 before.html
```
(the `mdn.html` and `mdn.html.gz` is from developer.mozilla.org and it's run in not-DEBUG mode)

Basically, this PR saves 87KB on the size of the HTML. 
But comparing the gzipped versions it's only a difference of 19KB. 

But perhaps I'm just measuring things wrong but what I am seeing is that the `<Article/>` component renders more times. I don't know why because the `document` prop isn't different. 
I put in `console.log("RENDERING Article", new Date());` before the `return` inside `article.jsx` and noticed that it ran differently. Not sure if it's user error or an actual subtle effect of the hydration. 

So is it worth the risk for 19KB? I'm starting to doubt that. What do you think @Gregoor ?

The thing is that Kuma sucks in the sense that it's hard to measure these things. We don't have it yet in Stumptown-renderer but we will in a near future; the ability to make two versions of the same site in equal contexts. Then you can put both versions into a thing like Lighthouse or SpeedCurve and get real data.

**Comment by Gregoor** [comment]
On average 3G speeds that'd be more than a quarter of a second, no? So that's imo significant enough to do it.

**Comment by tobinmori** [comment]
@peterbe is there a user story for this one? looks like #5613 is closed.

**Comment by peterbe** [comment]
> @peterbe is there a user story for this one? looks like #5613 is closed.

Yes, that was the user story. But that belonged to another user story which was that the React site was slow performing so we rushed at it with various little tricks to get it to be as fast as the Jinja based one. 

Generally, this PR is 90% of the way there but the last 10% is fraught with trouble. For one, we'rel not desperate for speed anymore and we can't decide if this is any good anyway (without a platform for experimentation).

**Pull request closed without merging**
