### PR TITLE
summary if nothing to highlight

### LINKED ISSUE #7756: Empty SERP
While I was researching something on MDN I noticed that some search results come up empty. Take https://developer.mozilla.org/en-US/search?q=media+overview for example:

empty-serp

What's going on here?
Can the situation be improved?

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #7756

It's a Draft because you can't test it until https://github.com/mdn/yari/pull/2712 lands and updates the ES servers. 

Basically, you should not be seeing any empty blocks under the title when you search for http://localhost.org:8000/en-US/search?q=media+overview&page=2

### CODE REVIEW

**Comment by peterbe** [comment]
@schalkneethling To be able to test this, you'll need to have the remote Dev `ES_URLS` value set. 
I kicked off a complete build of Dev so that'll make sure the data is available in that Elasticsearch instance (in a matter of 30min from right now).

**Comment by schalkneethling** [comment]
Screenshot showing search results with on result missing an excerpt

Using: http://localhost.org:8000/en-US/search?q=media+overview&page=2
For the second to last result, I still see the missing excerpt.

**Comment by peterbe** [comment]
@schalkneethling Can you check that you're running the right branch and stuff. This is what I see. 

Screen Shot 2021-01-28 at 10 52 58 AM

**Comment by schalkneethling** [comment]
> @schalkneethling Can you check that you're running the right branch and stuff. This is what I see.

I am on `7756-summary-if-nothing-to-highlight` and I did `docker-compose up -d` and I have `ES_URLS` in my `env`

**Comment by schalkneethling** [comment]
@peterbe Also, just did `git pull peterbe 7756-summary-if-nothing-to-highlight` and all is up to date

**Review by schalkneethling — APPROVED** [review]
It works 🎉

**Pull request merged**
