### PR TITLE
Re-introduce async GA tag

### PR DESCRIPTION
**Pull request by mindy**
The async tag did not impact performance, so adding it back in per the original ticket, #6253. 

Reverts https://github.com/mdn/kuma/pull/6601

### CODE REVIEW

**Comment by callahad** [comment]
Thank you!

**Comment by escattone** [comment]
Oops, this missed adding back the line:
```javascript
    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
```

I'm going to create/merge/deploy a quick PR to do that, since GA is broken on stage/prod.

**Comment by escattone** [comment]
See https://github.com/mdn/kuma/pull/6649

**Comment by callahad** [comment]
Gah, extremely sorry for missing that in review. Thank you for picking it
up.

**Pull request merged**
