### PR TITLE
redirect firefox accounts per mdn/kuma#7345

### LINKED ISSUE #7345: Remove old Firefox Accounts documentation
@clouserw commented on [Wed Jul 01 2020](https://github.com/mdn/sprints/issues/3459)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts

This page (and sub-pages) are about Firefox Accounts and are created from[ some outdated documentation](https://mozilla.github.io/application-services/docs/accounts/welcome.html) that we'll be removing soon.  Please remove these pages from MDN.  If possible, please redirect requests to our new documentation: https://mozilla.github.io/ecosystem-platform/docs/welcome

Thank you

/cc @rfk

---

@chrisdavidmills commented on [Thu Jul 02 2020](https://github.com/mdn/sprints/issues/3459#issuecomment-652873931)

Sure thing @clouserw ! I've moved these pages to the MDN archive already: https://wiki.developer.mozilla.org/en-US/docs/Archive/Mozilla/Firefox/Accounts

@escattone, please can you hard redirect the above page and all its children to https://mozilla.github.io/ecosystem-platform/docs/welcome ?

Thanks.

---

@escattone commented on [Thu Jul 02 2020](https://github.com/mdn/sprints/issues/3459#issuecomment-653098217)

Will do Dr. Mills! (aka @chrisdavidmills). I'll post a comment here when that's done.

### PR DESCRIPTION
**Pull request by escattone**
Fixes  #7345

### CODE REVIEW

**Comment by peterbe** [comment]
Note-to-self; here's what I found in the prod db as of July 14:
```
en-US  Archive/Mozilla/Firefox/Accounts
en-US  Archive/Mozilla/Firefox/Accounts/Atttached_APIs
en-US  Archive/Mozilla/Firefox/Accounts/Firefox_Accounts_End-to-end_encryption
en-US  Archive/Mozilla/Firefox/Accounts/Introduction
en-US  Archive/Mozilla/Firefox/Accounts/OAuth_dashboard
en-US  Archive/Mozilla/Firefox/Accounts/UX_Guidelines
en-US  Archive/Mozilla/Firefox/Accounts/WebExtensions
en-US  Mozilla/Firefox_Accounts
en-US  Mozilla/Firefox_Accounts_OAuth_Dashboard
en-US  Mozilla/Tech/Firefox_Accounts
en-US  Mozilla/Tech/Firefox_Accounts/Atttached_APIs
en-US  Mozilla/Tech/Firefox_Accounts/Firefox_Accounts_End-to-end_encryption
en-US  Mozilla/Tech/Firefox_Accounts/Introduction
en-US  Mozilla/Tech/Firefox_Accounts/OAuth_dashboard
en-US  Mozilla/Tech/Firefox_Accounts/UX_Guidelines
en-US  Mozilla/Tech/Firefox_Accounts/WebExtensions
pl     Mozilla/Firefox_Accounts
```

**Comment by escattone** [comment]
> What about `Mozilla/Firefox_Accounts_OAuth_Dashboard`?

Good catch! I'll add that one as well, thanks @peterbe!

**Comment by escattone** [comment]
Just FYI, @chrisdavidmills gave his approval via Slack.

**Pull request merged**
