### PR TITLE
serve file attachment redirects from a static config file

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Review by escattone — CHANGES_REQUESTED** [review]
@peterbe I think the mappings in the`redirects.json` file are off. For example, it provides `/attachments/2012/07/09/130/544165b82dc2d1e62e3fc8585b1ede4d/AlertHelloWorld.png` as the mapping for file `30`, but file `30` on MDN actually maps to `/attachments/2012/07/09/30/254c6e9125f12f6409dc6eccbdb15847/s-resize.gif`.

Similarly, file `15` is mapped to `/attachments/2012/07/09/127/893217a5a639ec149814450fdf858439/AIS_NewWindowIcon.png` but it should map to `/attachments/2012/07/09/15/95a308d2ce7fb13fba1f64fc45181af8/crosshair.gif`.

**Comment by peterbe** [comment]
> @peterbe I think the mappings in the`redirects.json` file are off. For example, it provides `/attachments/2012/07/09/130/544165b82dc2d1e62e3fc8585b1ede4d/AlertHelloWorld.png` as the mapping for file `30`, but file `30` on MDN actually maps to `/attachments/2012/07/09/30/254c6e9125f12f6409dc6eccbdb15847/s-resize.gif`.
> 
> Similarly, file `15` is mapped to `/attachments/2012/07/09/127/893217a5a639ec149814450fdf858439/AIS_NewWindowIcon.png` but it should map to `/attachments/2012/07/09/15/95a308d2ce7fb13fba1f64fc45181af8/crosshair.gif`.

No, you need to use the relevant URL. It's weird. Take `30` for example:

```
▶ xh https://developer.mozilla.org/@api/deki/files/30/=AlertHelloWorld.png
HTTP/2.0 301 Moved Permanently
location: https://mdn.mozillademos.org/files/130/AlertHelloWorld.png
...
```
```
▶ xh https://mdn.mozillademos.org/files/130/AlertHelloWorld.png
HTTP/2.0 302 Found
location: https://media.prod.mdn.mozit.cloud/attachments/2012/07/09/130/544165b82dc2d1e62e3fc8585b1ede4d/AlertHelloWorld.png
...
```

Regarding `30`, the way it appears in our content is like this:
```html
<img src="/@api/deki/files/30/=AlertHelloWorld.png">
```

Had you manually make the URL `'https://mdn.mozillademos.org/files/' + '30' + '/whatever'` you'd get:
```
▶ xh https://mdn.mozillademos.org/files/30/whatever
HTTP/2.0 302 Found
location: https://media.prod.mdn.mozit.cloud/attachments/2012/07/09/30/254c6e9125f12f6409dc6eccbdb15847/s-resize.gif
...
```

It also becomes more clear if you use `wget` to show the history:

```
▶ wget https://developer.mozilla.org/@api/deki/files/30/=AlertHelloWorld.png 2>&1 | rg -i location
Location: https://mdn.mozillademos.org/files/130/AlertHelloWorld.png [following]
Location: https://media.prod.mdn.mozit.cloud/attachments/2012/07/09/130/544165b82dc2d1e62e3fc8585b1ede4d/AlertHelloWorld.png [following]
```

Where it gets **extra confusing** is that things are different in my new kuma code. 
Because some redirects stemmed from 2 redirects and some stemmed from 1 redirect. E.g. `A -> B -> C` sometimes and `A -> C` sometimes. The `redirects.json` is already computed in a way that it's always `A -> C`. 
Proof:

```
# First that domain switching redirect:
▶ xh http://localhost.org:8000/@api/deki/files/30/=AlertHelloWorld.png
HTTP/1.1 301 Moved Permanently
location: http://demos:8000/files/30/AlertHelloWorld.png
...
```
...then... 
```
▶ xh http://demos:8000/files/30/AlertHelloWorld.png
HTTP/1.1 302 Found
location: https://media.prod.mdn.mozit.cloud/attachments/2012/07/09/130/544165b82dc2d1e62e3fc8585b1ede4d/AlertHelloWorld.png
...
```

So, either way from `` you end up actually downloading `attachments/2012/07/09/130/544165b82dc2d1e62e3fc8585b1ede4d/AlertHelloWorld.png` whose name makes perfect sense.

**Comment by peterbe** [comment]
@escattone Nothing's as easy as you think. 

To aid the testing, I fished out a couple of IDs that "clash". E.g. `5695`
Prior to the latest fix, 5695 would be the same ID both for a `mindtouch_attachment_id` and `attachment_id`. 

```
▶ xh http://localhost.org:8000/files/5695/down-white.png
HTTP/1.1 301 Moved Permanently
location: http://demos:8000/files/5695/down-white.png
```
and 
```
▶ xh http://demos:8000/files/5695/down-white.png
HTTP/1.1 302 Found
location: https://media.prod.mdn.mozit.cloud/attachments/2013/07/26/5695/b2bd677bcc33a1443a02cc0ed4d51dd3/down-white.png
```

And if you use the same ID with the `/@api/deki`

```
▶ xh http://localhost.org:8000/@api/deki/files/5695/=alpha.png
HTTP/1.1 302 Found
location: https://media.prod.mdn.mozit.cloud/attachments/2012/07/09/3402/b6ee2f795f152b91be88990c73457241/alpha.png
```

But note here that for `/@api/deki` URLs you're allowed to use the main host header. That's a slight deviation. 
That's because the `mindtouch_redirects.json` doesn't have the mapping to the relevant `attachment_id`. Instead, it goes straight to the S3 redirect.

**Comment by peterbe** [comment]
@escattone Another update. Now you're not allowed to use the main host with `/@api/deki` URLs. So this fixed the above-mentioned comment.

```
▶ xh http://localhost.org:8000/@api/deki/files/5695/\=alpha.png
HTTP/1.1 301 Moved Permanently
location: http://demos:8000/@api/deki/files/5695/=alpha.png
```
and
```
▶ xh http://demos:8000/@api/deki/files/5695/\=alpha.png
HTTP/1.1 302 Found
location: https://media.prod.mdn.mozit.cloud/attachments/2012/07/09/3402/b6ee2f795f152b91be88990c73457241/alpha.png
```

So we have full parity now!

**Review by escattone — APPROVED** [review]
FYI, @peterbe and I discussed this PR at length in a video call, which led to using two separate JSON redirects files.

**Pull request merged**
