### PR TITLE
github action that runs docker-compose

### PR DESCRIPTION
**Pull request by peterbe**
In TravisCI:

* Takes ~15min
* Sometimes doesn't update the PR that the tests have started | finished

In GitHub Actions:

* Takes ~15min
* All CI things

### CODE REVIEW

**Comment by peterbe** [comment]
Note-to-self; I can't figure out the denial to push so I filed: https://github.com/whoan/docker-build-with-cache-action/issues/65

**Comment by peterbe** [comment]
[Perhaps related](https://github.community/t/pulling-speed-is-same-as-dockerhub/130162/2). *"working on the GITHUB_TOKEN support"*

**Comment by peterbe** [comment]
[This one](https://github.com/mdn/kuma/pull/7486) is an attempt to try the same thing but from within the `mdn` repo rather than from a fork's branch to `mdn:master`.

**Review by alshamiri5 — APPROVED** [review]

**Comment by escattone** [comment]
Closing since replaced by #7486

**Pull request closed without merging**
