### PR TITLE
fix(styles): Remove now unnecessary `display: none;` declaration

### PR DESCRIPTION
**Pull request by ExE-Boss**
Addresses part of #6035

### CODE REVIEW

**Comment by ExE-Boss** [comment]
@peterbe That’d&nbsp;be&nbsp;https://github.com/mdn/kumascript/pull/963, https://github.com/mdn/kumascript/pull/983, https://github.com/mdn/kumascript/pull/984 and&nbsp;https://github.com/mdn/kumascript/pull/987, which&nbsp;also get&nbsp;rid ofof&nbsp;the&nbsp;second icon inside of&nbsp;the&nbsp;block&nbsp;indicator header&nbsp;text.

**Comment by schalkneethling** [comment]
@ExE-Boss with https://github.com/mdn/kumascript/pull/1264 merged, do we still need this PR? Apologies for the long delay in getting back to you.

**Comment by ExE-Boss** [comment]
We&nbsp;can re‑tool&nbsp;it to&nbsp;remove the&nbsp;now‑unnecessary `display: none;`&nbsp;declaration: https://github.com/mdn/kuma/blob/1d2c7d6f4425572629148e172e98308dd827e09b/kuma/static/styles/includes/_mixins_indicators.scss#L96-L98

**Comment by schalkneethling** [comment]
> We can re‑tool it to remove the now‑unnecessary `display: none;` declaration:
> 
> https://github.com/mdn/kuma/blob/1d2c7d6f4425572629148e172e98308dd827e09b/kuma/static/styles/includes/_mixins_indicators.scss#L96-L98
> 
> That way, it becomes possible to use inline icon macros inside `.blockIndicator.note` and `.blockIndicator.warning` blocks.

Sounds good to me @ExE-Boss, let's do that.

**Pull request merged**
