### PR TITLE
Add new l10n survey banner

### LINKED ISSUE #7315: T - l10n survey
Need to add the l10n survey to MDN using the same banner mechanics as needs assessment and subscriptions.

Wording and layout provided by @malqinneh via Slack:

988D72B8-5116-4CCB-9D3D-37C7735035B9

## Acceptance Criteria

- [ ] l10n survey live on all MDN pages as a dismissable banner in the footer of the viewport
- [ ] Able to turn the survey on and off via the waffle flag l10n-survey

### PR DESCRIPTION
**Pull request by schalkneethling**
Add new l10n survey banner behind the l10n_survey waffle flag

@Gregoor r? This should ideally go out today.

fix #7315

- [ ] Waiting on survey URL

### CODE REVIEW

**Comment by schalkneethling** [comment]
> Two things, a change request and a nit (in that order):
> 
> 1. this still needs a migration adding the waffle flag for the banner (the developer_needs flag migration could serve as a template)

Yup, now I need to remember how to do that :)

> 2. some of the CSS seems to be similar to another banner's CSS, maybe worth sharing those styles (might also not be worth it, so def feel free to say no to this one 😁 )

This one is temporary and short-lived so I am ok with some duplication. I believe it is mainly around the CTA button.

> 
> Oh and the URL is still TODO

:+1:

**Comment by schalkneethling** [comment]
@Gregoor - Thank you for the review. I have added the migration. Waiting on the URL. Will update and let you know once that has been added should you need one more pass 🌮

**Comment by peterbe** [comment]
Shall we revert this once the survey time is over or is this change here to stay?

**Comment by schalkneethling** [comment]
> Shall we revert this once the survey time is over or is this change here to stay?

We can revert. I will confirm the duration.

**Comment by schalkneethling** [comment]
@malqinneh Two things needed here:

1. The URL for the survey
2. How long should the survey run for

Thank you

**Comment by malqinneh** [comment]
Survey link: https://s2.userzoom.com/m/MSBDNTgxMlMxMzMg
I have an auto stop at 50 results/participants. That being said, let's plan to stop the survey by Tuesday, July 14 at latest (in case we don't get our desired results filled).

**Comment by schalkneethling** [comment]
@Gregoor this one is ready when you are 😸

**Pull request merged**
