### PR TITLE
First iteration of responsive header improvements

### PR DESCRIPTION
**Pull request by schalkneethling**
I am breaking down the work on the optimized header as I have found a few things over and above the "actual" work that needs attention. So, instead of holding out for one *big* PR, I am thinking many small pull requests that progressively improve things ;)

## Header on mobile post this PR (not signed in)

Screenshot 2020-05-04 at 06 43 02

## Header on mobile post this PR (signed in)

Screenshot 2020-05-04 at 06 42 47

@Gregoor r?

### CODE REVIEW

**Comment by Gregoor** [comment]
The header grew on prod for me and it looks like the snapshots need to be updated. No qualms otherwise.

## This PR
Screenshot_2020-05-04 MDN Web Docs

## Prod
Screenshot_2020-05-04 MDN Web Docs(1)

**Comment by schalkneethling** [comment]
> The header grew on desktop for me (see below) and it looks like the snapshots need to be updated. No qualms otherwise.

Whoops, need to adjust the padding for tablet and up. Will update snapshot

**Comment by schalkneethling** [comment]
@Gregoor ready for another round.

**Comment by Gregoor** [comment]
Looks good now 👌 Are there also designs I could check these changes against?

**Comment by schalkneethling** [comment]
> Looks good now 👌 Are there also designs I could check these changes against?

Yup, but this does not quite get us there yet. There is a lot to do so, I am progressively enhancing the header in multiple pull requests. For future reference though, see https://github.com/mdn/kuma/issues/6784

**Comment by Gregoor** [comment]
Thanks for the link! I got a bit of a padding nit then. Looking at the designs, they seem to have less space between the user avatar/name and the menu items (i.e. Technologies, etc.)

**Comment by schalkneethling** [comment]
> Thanks for the link! I got a bit of a padding nit then. Looking at the designs, they seem to have less space between the user avatar/name and the menu items (i.e. Technologies, etc.)

Yeah, I made a bit of an executive decision so there is a larger touch area. Generally a good thing but especially for accessibility.

**Pull request merged**
